name: C++ CI (Multi-folder)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: Checks ${{ matrix.folder }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        folder: [englorus, polynomial]

    steps:
    - name: Code download
      uses: actions/checkout@v4

    - name: Installing dependencies (CMake, GCC, Doxygen)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ doxygen

    - name: CMakeLists.txt check
      id: check_cmake
      run: |
        if [ -f "${{ matrix.folder }}/CMakeLists.txt" ]; then
          echo "has_cmake=true" >> $GITHUB_OUTPUT
        else
          echo "has_cmake=false" >> $GITHUB_OUTPUT
          echo "CMakeLists.txt not found ${{ matrix.folder }}, CMake build skipped"
        fi

    - name: CMake configuration
      if: steps.check_cmake.outputs.has_cmake == 'true'
      run: cmake -B ${{ matrix.folder }}/build -S ${{ matrix.folder }} -DBUILD_TESTING=OFF -DUNITTEST_BUILD_TESTS=OFF

    - name: Project build
      if: steps.check_cmake.outputs.has_cmake == 'true'
      run: cmake --build ${{ matrix.folder }}/build --config Release

    - name: Tests
      if: steps.check_cmake.outputs.has_cmake == 'true'
      run: ctest --test-dir ${{ matrix.folder }}/build --output-on-failure || true

    - name: Doxygen generation check
      run: |
        if [ -f "${{ matrix.folder }}/Doxyfile" ]; then
          echo "Doxygen generation for ${{ matrix.folder }}..."
          cd ${{ matrix.folder }} && doxygen Doxyfile
          echo "Doxygen for ${{ matrix.folder }} is built succesfully"
        else
          echo "ℹDoxyfile not found ${{ matrix.folder }}, skipping..."
        fi